### ISSUE TITLE
One link

### ISSUE THREAD

**Issue by TechnologyClassroom** [reHackable/awesome-reMarkable#128]
I have two links that could go on your awesome list.

* [Adding a microSD card](http://www.davisr.me/projects/remarkable-microsd/)
* <strike>[reMarkable's sources](https://remarkable.engineering/deploy/)</strike>

**Comment by Ameb** [comment]
You could comment on #62 asking to reopen the issue. This issue is a duplicate but I didn't gave any reason to close the issue. My apologies.

Have you checked your second link? reMarkable AS removed the enginnering webpage and we don't have an easy way to list shared toolchains or update images (that would break the ToS actually).

For the Davis blogpost I will gladly accept a pull request, as long as it names the reMarkable 1 in the description.

**Comment by TechnologyClassroom** [comment]
@Ameb Cool, I will make a PR later.

Talk on closed issues usually goes unnoticed and ignored unless it includes topics that are commonly searched for.

I removed my second link as I could not find an alternative in the wayback machine.

**Comment by Eeems** [comment]
@TechnologyClassroom it's probably fine to close this now, right?
