### ISSUE TITLE
I would love to be a contributor for this project. I am the owner of einkpads.com 

### ISSUE THREAD

**Issue by ceigon01** [reHackable/awesome-reMarkable#9]

**Comment by Ameb** [comment]
Could you please explain what do you mean?

The software you have developed looks good. You can collaborate with the remarkable open source community improving the code in the other repositories.

I am against the idea of your webpage being listed here, since your tool is not open source. Not sure if that is what you are looking for. This is just my personal opinion.

**Comment by CTXz** [comment]
I agree with @Ameb, I'm not willing to list proprietary works. This organisation is about OSS, not advertisement!
